version: '3.1'

services:
  crab-in-a-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '7003:5432'
    volumes:
      - crab-in-a-db:/var/lib/postgresql/data

volumes:
  crab-in-a-db: